import Head from "next/head";
import Container from "@/Tags/Container/Container";
import styled from "styled-components";
import View from "@/Tags/View/View";
import { Text } from "@/Tags/Text/Text";

export default function Home() {
  const Main = styled.main``;
  return (
    <>
      <Head>
        {/* <title>Expert || Any Service | Any Time | Any Where</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
        <script
          src="https://www.google.com/recaptcha/api.js"
          async
          defer
        ></script>
      </Head>
      <Main>
        <Text>Home page</Text>
      </Main>
    </>
  );
}
